# Generated by Django 4.0.2 on 2022-02-28 11:23

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='All1ZedEventsCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_commission', models.IntegerField(default=8)),
            ],
            options={
                'verbose_name': 'All1Zed Events Commission',
                'verbose_name_plural': 'All1Zed Events Commission',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the Event must be descriptive and not misleading.', max_length=50, verbose_name='Event Name')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('venue', models.CharField(help_text='Please specify the name of the place.', max_length=255)),
                ('venue_location', models.CharField(blank=True, help_text='Please paste the google maps coordinates', max_length=50, null=True)),
                ('organizer', models.CharField(max_length=255, verbose_name='Who is the Organizer of this Event?')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='events/images', verbose_name='Upload a Banner Image for this Event')),
                ('date_time_published', models.DateTimeField(auto_now_add=True)),
                ('date_starting', models.DateField(verbose_name='When is this Event starting?')),
                ('time_starting', models.TimeField(verbose_name='At what time will this event start')),
                ('date_ending', models.DateField(verbose_name='When will this Event close?')),
                ('time_ending', models.TimeField(verbose_name='At what time will this Event close?')),
                ('vvip_ticket_price', models.IntegerField(verbose_name='VVIP Ticket Price')),
                ('vip_ticket_price', models.IntegerField(help_text='Price is in Zambian Kwacha (ZMW)', verbose_name='VIP Ticket Price')),
                ('general_ticket_price', models.IntegerField(help_text='Price is in Zambian Kwacha (ZMW)', verbose_name='General Ticket Price (Ordinary)')),
                ('sitting_plan', models.FileField(blank=True, null=True, upload_to='')),
                ('age_or_gender_restriction', models.CharField(choices=[('18 Years And Above', '18 Years And Above'), ('Everyone', 'Everyone'), ('16 Years And Above', '16 Years And Above'), ('Males Only', 'Males Only'), ('Females Only', 'Females Only')], help_text='Who is Eligible to attend this Event?', max_length=255)),
                ('additional_information', ckeditor_uploader.fields.RichTextUploadingField()),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'My Events',
            },
        ),
        migrations.CreateModel(
            name='EventTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('VVIP', 'VVIP'), ('VIP', 'VIP'), ('General', 'General')], max_length=20)),
                ('ticket_price', models.IntegerField(editable=False)),
                ('datetime_bought', models.DateTimeField(auto_now_add=True)),
                ('client_first_name', models.CharField(max_length=50)),
                ('client_last_name', models.CharField(max_length=50)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            options={
                'verbose_name_plural': 'Events Tickets',
            },
        ),
    ]
