# Generated by Django 4.0.2 on 2022-02-23 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='age_or_gender_restriction',
            field=models.CharField(choices=[('18 Years And Above', '18 Years And Above'), ('Everyone', 'Everyone'), ('16 Years And Above', '16 Years And Above'), ('Males Only', 'Males Only'), ('Females Only', 'Females Only')], help_text='Who is Eligible to attend this Event?', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='events/images', verbose_name='Upload a Banner Image for this Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_ending',
            field=models.DateField(verbose_name='When will this Event close?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_starting',
            field=models.DateField(verbose_name='When is this Event starting?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Give a detailed description about this event.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text='The name of the Event must be descriptive and not misleading.', max_length=255, verbose_name='Name of The Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ordinary_ticket_price',
            field=models.IntegerField(help_text='Price is in Zambian Kwacha (ZMW)', verbose_name='Ticket Price for Ordinary'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.CharField(max_length=255, verbose_name='Who is the Organizer of this Event?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_ending',
            field=models.TimeField(verbose_name='At what time will this Event close?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_starting',
            field=models.TimeField(verbose_name='At what time will this event start'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(help_text='Please specify the location of this event with full details.', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='vip_ticket_price',
            field=models.IntegerField(help_text='Price is in Zambian Kwacha (ZMW)', verbose_name='Ticket Price for VIPs'),
        ),
    ]
