# Generated by Django 4.0.2 on 2022-02-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventticket',
            name='type',
            field=models.CharField(choices=[('VVIP', 'VVIP'), ('VIP', 'VIP'), ('General', 'General')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
