# Generated by Django 4.0.2 on 2022-02-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventticket_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ordinary_ticket_price',
        ),
        migrations.AddField(
            model_name='event',
            name='general_ticket_price',
            field=models.IntegerField(default=200, help_text='Price is in Zambian Kwacha (ZMW)', verbose_name='General Ticket Price (Ordinary)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='vvip_ticket_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='VVIP Ticket Price'),
        ),
        migrations.AddField(
            model_name='eventticket',
            name='ticket_price',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='vip_ticket_price',
            field=models.IntegerField(help_text='Price is in Zambian Kwacha (ZMW)', verbose_name='VIP Ticket Price'),
        ),
    ]
