# Generated by Django 4.0.2 on 2022-02-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_event_ordinary_ticket_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='All1ZedEventsCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_commission', models.IntegerField(default=8)),
            ],
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name_plural': 'My Events'},
        ),
        migrations.AlterModelOptions(
            name='eventticket',
            options={'verbose_name_plural': 'Events Tickets'},
        ),
        migrations.AlterField(
            model_name='eventticket',
            name='ticket_price',
            field=models.IntegerField(editable=False),
        ),
    ]
