# Generated by Django 4.0.2 on 2022-02-24 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_all1zedeventscommission_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='all1zedeventscommission',
            options={'verbose_name': 'All1Zed Events Commission', 'verbose_name_plural': 'All1Zed Events Commission'},
        ),
    ]
