# Generated by Django 4.0.2 on 2022-02-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_all1zedeventscommission_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text='The name of the Event must be descriptive and not misleading.', max_length=50, verbose_name='Event Name'),
        ),
    ]
