# Generated by Django 4.0.2 on 2022-02-25 10:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_event_additional_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='additional_information',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
