# Generated by Django 4.0.4 on 2022-05-05 14:05

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_terms_and_conditions', ckeditor_uploader.fields.RichTextUploadingField(help_text='Elaborate the Terms and Conditions Buyers are subjects to. Please be clear in your explanation.')),
                ('event_organizer_terms_and_conditions', ckeditor_uploader.fields.RichTextUploadingField(help_text='Terms and Conditions for Event Owners. This must be clear and straight forward to understand.')),
                ('privacy_policy', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Describe how you shall maintain security on the information that users are proving to All1Zed Events Platform.', null=True)),
                ('terms_of_use', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='By using All1Zed Events Platform, all stakeholders agree to your specific terms. Describe them here.', null=True)),
            ],
            options={
                'verbose_name': 'Terms And Conditions',
                'verbose_name_plural': 'Terms And Conditions',
            },
        ),
    ]
