# Generated by Django 4.0.4 on 2022-05-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='All1zedEventCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_per_ticket', models.FloatField(default=10, help_text='This designates the amount in Zambian Kwacha, that ALl1Zed gets for each Ticket sold on the platform.')),
            ],
            options={
                'verbose_name': 'Bus Ticket Commission',
                'verbose_name_plural': ' All1Zed Bus Ticket Commission',
            },
        ),
    ]
