# Generated by Django 4.0.4 on 2022-05-05 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0002_all1zedeventcommission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='All1zedEventCommission',
            new_name='All1zedBusCommission',
        ),
    ]
