# Generated by Django 4.0.4 on 2022-05-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0003_rename_all1zedeventcommission_all1zedbuscommission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all1zedbuscommission',
            name='commission_per_ticket',
            field=models.FloatField(default=10, help_text='This designates the amount in Zambian Kwacha, that All1Zed gets for each Ticket sold on the platform.'),
        ),
    ]
