# Generated by Django 4.0.4 on 2022-05-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0004_alter_all1zedbuscommission_commission_per_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('session_uuid', models.CharField(max_length=255)),
                ('date_time_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('successful', 'successful'), ('failed', 'failed')], max_length=50)),
                ('product_id', models.IntegerField()),
                ('amount', models.FloatField()),
                ('phone_number', models.IntegerField()),
                ('type', models.CharField(choices=[('cash_in', 'cash_in'), ('payment', 'payment')], max_length=255)),
                ('request_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_reference', models.CharField(max_length=255)),
            ],
        ),
    ]
