# Generated by Django 4.0.4 on 2022-05-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0005_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
