# Generated by Django 4.0.2 on 2022-02-13 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bus_full_name', models.CharField(max_length=50)),
                ('bus_short_name', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('number_of_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BusCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_phone_number', models.CharField(max_length=50)),
                ('company_email', models.EmailField(max_length=64)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_place', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='buses.bus')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('paid', models.BooleanField()),
                ('date_bought', models.DateField()),
                ('passenger_first_name', models.CharField(max_length=50)),
                ('passenger_last_name', models.CharField(max_length=50)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('seat_number', models.IntegerField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buses.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buses.route')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('is_available', models.BooleanField()),
                ('verbose_name', models.CharField(blank=True, max_length=50, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buses.bus')),
            ],
        ),
        migrations.CreateModel(
            name='BusImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tickets/buses')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='buses.bus')),
            ],
        ),
        migrations.CreateModel(
            name='BusCompanyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tickets/buscompanies')),
                ('bus_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='buses.buscompany')),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='buses.buscompany'),
        ),
    ]
