# Generated by Django 4.0.4 on 2022-07-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='bus_short_name',
        ),
        migrations.AddField(
            model_name='bus',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
