# Generated by Django 4.0.2 on 2022-02-28 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='departure_time',
        ),
    ]
