# Generated by Django 4.0.2 on 2022-02-10 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='to',
            new_name='destination',
        ),
        migrations.RemoveField(
            model_name='buscompany',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='buscompany',
            name='number_of_buses',
        ),
        migrations.RemoveField(
            model_name='route',
            name='full_route_name',
        ),
        migrations.CreateModel(
            name='BusImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tickets/buses')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='buses.bus')),
            ],
        ),
        migrations.CreateModel(
            name='BusCompanyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tickets/buscompanies')),
                ('bus_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='buses.buscompany')),
            ],
        ),
    ]
