# Generated by Django 4.0.2 on 2022-02-14 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buses', '0002_buscompany_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name_plural': 'Buses'},
        ),
        migrations.AlterModelOptions(
            name='buscompany',
            options={'verbose_name_plural': 'Bus Companies'},
        ),
        migrations.AlterField(
            model_name='buscompany',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Login Username'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
