# Generated by Django 4.0.2 on 2022-02-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_remove_ticket_departure_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='passenger_phone',
            field=models.CharField(default='0971977252', max_length=12),
            preserve_default=False,
        ),
    ]
