# Generated by Django 4.0.2 on 2022-02-28 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_ticket_passenger_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buscompanyimage',
            name='bus_company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='buses.buscompany'),
        ),
        migrations.AlterField(
            model_name='busimage',
            name='bus',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='buses.bus'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
