# Generated by Django 4.0.2 on 2022-02-12 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_alter_buscompany_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buscompanyimage',
            name='bus_company',
        ),
        migrations.DeleteModel(
            name='BusCompany',
        ),
        migrations.DeleteModel(
            name='BusCompanyImage',
        ),
    ]
