# Generated by Django 4.0.2 on 2022-02-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_alter_bus_options_alter_buscompany_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='paid',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_bought',
            field=models.DateField(auto_now_add=True),
        ),
    ]
