# Generated by Django 4.0.2 on 2022-03-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0004_alter_buscompanyimage_bus_company_alter_busimage_bus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buscompanyimage',
            name='image',
            field=models.ImageField(upload_to='tickets/buscompanies', verbose_name='Upload Company Logo'),
        ),
        migrations.AlterField(
            model_name='busimage',
            name='image',
            field=models.ImageField(upload_to='tickets/buses', verbose_name='Upload Bus Image'),
        ),
    ]
