# Generated by Django 4.0.2 on 2022-02-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0004_remove_buscompanyimage_bus_company_delete_buscompany_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
