# Generated by Django 4.0.2 on 2022-03-05 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0005_alter_buscompanyimage_image_alter_busimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buscompanyimage',
            name='bus_company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bus_company_image', to='buses.buscompany'),
        ),
    ]
