# Generated by Django 4.0.2 on 2022-03-08 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0006_alter_buscompanyimage_bus_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FullyBookedBus',
        ),
    ]
