# Generated by Django 4.0.2 on 2022-03-08 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0008_fullybookedbus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='bus',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='buses.bus'),
        ),
    ]
